name: simple_timer_count_down
description: "Simple timer count down. Easy to use and simple to implement."
version: 1.0.2
homepage: https://github.com/adarshneeds/simple_timer_count_down

license: MIT

environment:
  sdk: ^3.5.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  
flutter: